robot_scan:
  group_name: manipulator_ensenso
  move_scan_vel_scaling: 0.3
  home_position: home_asus
  world_frame: world_frame
  tcp_frame: ensenso_move_frame
  planner_id: PTP
  tcp_to_cam_pose:
    trans:
      x: 0
      y: 0
      z: 0
    quat:
      x: 0
      y: 0
      z: 0
      w: 1
  world_to_obj_pose:
    trans:
      x: 0.0
      y: -0.4
      z: 0.18
    quat:
      x: 0
      y: 0
      z: 0
      w: 1
  cam_to_obj_zoffset: 0.4
  cam_to_obj_xoffset: 0.065
  cam_tilt_angle: 1.57
  sweep_angle_start: 0
  sweep_angle_end: 6.28
  scan_topic: /point_cloud_workspace
  scan_target_frame: world_frame
  reachable_scan_points_ratio: 1.0
  stop_on_planning_error: true
  num_scan_points: 4
